---
- name: Create Directory
  hosts: windows
  tasks:
    - name: Create temp directory
      ansible.windows.win_file:
        path: C:\temp
        state: directory

- name: Place test.txt on Windows desktop
  hosts: windows
  tasks:
    - name: Create test.txt on desktop
      ansible.windows.win_copy:
        content: "This is a test file created by Ansible."
        dest: 'C:\temp\test.txt'